on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

name: CI

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Install Node
        uses: actions/setup-node@v2
        with:
          node-version: "16"

      - name: Install Yarn
        run: |
          npm install -g yarn
          yarn set version 3.4.1

      - name: Install dependencies
        run: yarn install

      - name: Get latest commit SHA of main branch
        id: get_sha
        run: echo "::set-output name=sha::$(git rev-parse origin/main)"

      - name: Build and test affected
        run: |
          if [[ "${{ github.event_name }}" == "pull_request" ]]; then
           HEAD_SHA=${{ github.event.pull_request.head.sha }}
           BASE_SHA=${{ steps.get_sha.outputs.sha }}
          else
           HEAD_SHA=${{ github.sha }}
           BASE_SHA=$(git rev-parse HEAD~1)
          fi
           yarn nx affected --target=build --base=$BASE_SHA --head=$HEAD_SHA
